#!/bin/bash




# we want caesar to take in parameters and then trim the required ammount
# We will find out what to trim by calling the create_pattern file and storing its output

#!/bin/bash


# for this function we want to take two parameters k and u

uppercase=1
offset=0
while getopts k:u flag
do
	case "${flag}" in 
		k) offset=${OPTARG};;
		u) uppercase=0;;
	esac
done

# echo "$offset"
# echo "$uppercase"
declare pattern;
# if uppercase is true then our values range from 65-90: with an increment of 1
if (($uppercase==0))
then
	pattern=$(./create_pattern -k ${offset} -u);
	while IFS= read -r line
	do

		echo ${line} | tr '[A-Z]' '[${pattern}]'
	done
fi

# if uppercase is false then our values range from 97-122
if (($uppercase==1))
then
	pattern=$(./create_pattern -k ${offset});
	echo $pattern
	while IFS= read -r line
	do
		echo ${line} | tr '[a-z]' '[${pattern}]'
	done
fi

echo $pattern
# # echo $pattern

